name: Build Releases

on:
  push:
    tags:
      - v*

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: go-build-{{ checksum "build-release.sh" }}
          path: |
            ~/.cache/go-build
      - run: ./build-release.sh
        name: Run Build
      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/server_*
            build/client_*
