name: Build Releases

on:
  push:
    tags:
      - v*

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: go-build-{{ checksum "build-release.sh" }}
          path: |
            ~/.cache/go-build
      - run: ./build-release.sh
        name: Run Build
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            build/server_*
            build/client_*
